# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.admin_state_pac import AdminStatePac  # noqa: F401,E501
from tapi_server.models.capacity import Capacity  # noqa: F401,E501
from tapi_server.models.capacity_pac import CapacityPac  # noqa: F401,E501
from tapi_server.models.cost_characteristic import CostCharacteristic  # noqa: F401,E501
from tapi_server.models.latency_characteristic import LatencyCharacteristic  # noqa: F401,E501
from tapi_server.models.name_and_value import NameAndValue  # noqa: F401,E501
from tapi_server.models.node_edge_point import NodeEdgePoint  # noqa: F401,E501
from tapi_server.models.node_rule_group import NodeRuleGroup  # noqa: F401,E501
from tapi_server.models.resource_spec import ResourceSpec  # noqa: F401,E501
from tapi_server.models.transfer_cost_pac import TransferCostPac  # noqa: F401,E501
from tapi_server.models.transfer_integrity_pac import TransferIntegrityPac  # noqa: F401,E501
from tapi_server.models.transfer_timing_pac import TransferTimingPac  # noqa: F401,E501
from tapi_server import util
try:
    from itertools import imap
except ImportError:
    # Python 3...
    imap=map


class Node(Model):
    u"""NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, name=None, administrative_state=None, operational_state=None, lifecycle_state=None, total_potential_capacity=None, available_capacity=None, cost_characteristic=None, error_characteristic=None, loss_characteristic=None, repeat_delivery_characteristic=None, delivery_order_characteristic=None, unavailable_time_characteristic=None, server_integrity_process_characteristic=None, latency_characteristic=None, owned_node_edge_point=[], aggregated_node_edge_point=None, node_rule_group=None, encap_topology=None, layer_protocol_name=[]):  # noqa: E501
        u"""Node - a model defined in Swagger

        :param uuid: The uuid of this Node.  # noqa: E501
        :type uuid: str
        :param name: The name of this Node.  # noqa: E501
        :type name: List[NameAndValue]
        :param administrative_state: The administrative_state of this Node.  # noqa: E501
        :type administrative_state: str
        :param operational_state: The operational_state of this Node.  # noqa: E501
        :type operational_state: str
        :param lifecycle_state: The lifecycle_state of this Node.  # noqa: E501
        :type lifecycle_state: str
        :param total_potential_capacity: The total_potential_capacity of this Node.  # noqa: E501
        :type total_potential_capacity: Capacity
        :param available_capacity: The available_capacity of this Node.  # noqa: E501
        :type available_capacity: Capacity
        :param cost_characteristic: The cost_characteristic of this Node.  # noqa: E501
        :type cost_characteristic: List[CostCharacteristic]
        :param error_characteristic: The error_characteristic of this Node.  # noqa: E501
        :type error_characteristic: str
        :param loss_characteristic: The loss_characteristic of this Node.  # noqa: E501
        :type loss_characteristic: str
        :param repeat_delivery_characteristic: The repeat_delivery_characteristic of this Node.  # noqa: E501
        :type repeat_delivery_characteristic: str
        :param delivery_order_characteristic: The delivery_order_characteristic of this Node.  # noqa: E501
        :type delivery_order_characteristic: str
        :param unavailable_time_characteristic: The unavailable_time_characteristic of this Node.  # noqa: E501
        :type unavailable_time_characteristic: str
        :param server_integrity_process_characteristic: The server_integrity_process_characteristic of this Node.  # noqa: E501
        :type server_integrity_process_characteristic: str
        :param latency_characteristic: The latency_characteristic of this Node.  # noqa: E501
        :type latency_characteristic: List[LatencyCharacteristic]
        :param owned_node_edge_point: The owned_node_edge_point of this Node.  # noqa: E501
        :type owned_node_edge_point: List[NodeEdgePoint]
        :param aggregated_node_edge_point: The aggregated_node_edge_point of this Node.  # noqa: E501
        :type aggregated_node_edge_point: List[str]
        :param node_rule_group: The node_rule_group of this Node.  # noqa: E501
        :type node_rule_group: List[NodeRuleGroup]
        :param encap_topology: The encap_topology of this Node.  # noqa: E501
        :type encap_topology: str
        :param layer_protocol_name: The layer_protocol_name of this Node.  # noqa: E501
        :type layer_protocol_name: List[str]
        """
        self.swagger_types = {
            u'uuid': str,
            u'name': List[NameAndValue],
            u'administrative_state': str,
            u'operational_state': str,
            u'lifecycle_state': str,
            u'total_potential_capacity': Capacity,
            u'available_capacity': Capacity,
            u'cost_characteristic': List[CostCharacteristic],
            u'error_characteristic': str,
            u'loss_characteristic': str,
            u'repeat_delivery_characteristic': str,
            u'delivery_order_characteristic': str,
            u'unavailable_time_characteristic': str,
            u'server_integrity_process_characteristic': str,
            u'latency_characteristic': List[LatencyCharacteristic],
            u'owned_node_edge_point': List[NodeEdgePoint],
            u'aggregated_node_edge_point': List[str],
            u'node_rule_group': List[NodeRuleGroup],
            u'encap_topology': str,
            u'layer_protocol_name': List[str]
        }

        self.attribute_map = {
            u'uuid': u'uuid',
            u'name': u'name',
            u'administrative_state': u'administrative-state',
            u'operational_state': u'operational-state',
            u'lifecycle_state': u'lifecycle-state',
            u'total_potential_capacity': u'total-potential-capacity',
            u'available_capacity': u'available-capacity',
            u'cost_characteristic': u'cost-characteristic',
            u'error_characteristic': u'error-characteristic',
            u'loss_characteristic': u'loss-characteristic',
            u'repeat_delivery_characteristic': u'repeat-delivery-characteristic',
            u'delivery_order_characteristic': u'delivery-order-characteristic',
            u'unavailable_time_characteristic': u'unavailable-time-characteristic',
            u'server_integrity_process_characteristic': u'server-integrity-process-characteristic',
            u'latency_characteristic': u'latency-characteristic',
            u'owned_node_edge_point': u'owned-node-edge-point',
            u'aggregated_node_edge_point': u'aggregated-node-edge-point',
            u'node_rule_group': u'node-rule-group',
            u'encap_topology': u'encap-topology',
            u'layer_protocol_name': u'layer-protocol-name'
        }

        self._uuid = uuid
        self._name = name
        self._administrative_state = administrative_state
        self._operational_state = operational_state
        self._lifecycle_state = lifecycle_state
        self._total_potential_capacity = total_potential_capacity
        self._available_capacity = available_capacity
        self._cost_characteristic = cost_characteristic
        self._error_characteristic = error_characteristic
        self._loss_characteristic = loss_characteristic
        self._repeat_delivery_characteristic = repeat_delivery_characteristic
        self._delivery_order_characteristic = delivery_order_characteristic
        self._unavailable_time_characteristic = unavailable_time_characteristic
        self._server_integrity_process_characteristic = server_integrity_process_characteristic
        self._latency_characteristic = latency_characteristic
        self._owned_node_edge_point = owned_node_edge_point
        self._aggregated_node_edge_point = aggregated_node_edge_point
        self._node_rule_group = node_rule_group
        self._encap_topology = encap_topology
        self._layer_protocol_name = layer_protocol_name

    @classmethod
    def from_dict(cls, dikt):
        u"""Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The node of this Node.  # noqa: E501
        :rtype: Node
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        u"""Gets the uuid of this Node.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity. UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters. Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}  Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :return: The uuid of this Node.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        u"""Sets the uuid of this Node.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity. UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters. Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}  Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :param uuid: The uuid of this Node.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def name(self):
        u"""Gets the name of this Node.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :return: The name of this Node.
        :rtype: List[NameAndValue]
        """
        return self._name

    @name.setter
    def name(self, name):
        u"""Sets the name of this Node.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :param name: The name of this Node.
        :type name: List[NameAndValue]
        """

        self._name = name

    @property
    def administrative_state(self):
        u"""Gets the administrative_state of this Node.


        :return: The administrative_state of this Node.
        :rtype: str
        """
        return self._administrative_state

    @administrative_state.setter
    def administrative_state(self, administrative_state):
        u"""Sets the administrative_state of this Node.


        :param administrative_state: The administrative_state of this Node.
        :type administrative_state: str
        """
        allowed_values = [u"LOCKED", u"UNLOCKED"]  # noqa: E501
        if administrative_state not in allowed_values:
            raise ValueError(
                u"Invalid value for `administrative_state` ({0}), must be one of {1}"
                .format(administrative_state, allowed_values)
            )

        self._administrative_state = administrative_state

    @property
    def operational_state(self):
        u"""Gets the operational_state of this Node.


        :return: The operational_state of this Node.
        :rtype: str
        """
        return self._operational_state

    @operational_state.setter
    def operational_state(self, operational_state):
        u"""Sets the operational_state of this Node.


        :param operational_state: The operational_state of this Node.
        :type operational_state: str
        """
        allowed_values = [u"DISABLED", u"ENABLED"]  # noqa: E501
        if operational_state not in allowed_values:
            raise ValueError(
                u"Invalid value for `operational_state` ({0}), must be one of {1}"
                .format(operational_state, allowed_values)
            )

        self._operational_state = operational_state

    @property
    def lifecycle_state(self):
        u"""Gets the lifecycle_state of this Node.


        :return: The lifecycle_state of this Node.
        :rtype: str
        """
        return self._lifecycle_state

    @lifecycle_state.setter
    def lifecycle_state(self, lifecycle_state):
        u"""Sets the lifecycle_state of this Node.


        :param lifecycle_state: The lifecycle_state of this Node.
        :type lifecycle_state: str
        """
        allowed_values = [u"PLANNED", u"POTENTIAL_AVAILABLE", u"POTENTIAL_BUSY", u"INSTALLED", u"PENDING_REMOVAL"]  # noqa: E501
        if lifecycle_state not in allowed_values:
            raise ValueError(
                u"Invalid value for `lifecycle_state` ({0}), must be one of {1}"
                .format(lifecycle_state, allowed_values)
            )

        self._lifecycle_state = lifecycle_state

    @property
    def total_potential_capacity(self):
        u"""Gets the total_potential_capacity of this Node.

        An optimistic view of the capacity of the TopologicalEntity assuming that any shared capacity is available to be taken.  # noqa: E501

        :return: The total_potential_capacity of this Node.
        :rtype: Capacity
        """
        return self._total_potential_capacity

    @total_potential_capacity.setter
    def total_potential_capacity(self, total_potential_capacity):
        u"""Sets the total_potential_capacity of this Node.

        An optimistic view of the capacity of the TopologicalEntity assuming that any shared capacity is available to be taken.  # noqa: E501

        :param total_potential_capacity: The total_potential_capacity of this Node.
        :type total_potential_capacity: Capacity
        """

        self._total_potential_capacity = total_potential_capacity

    @property
    def available_capacity(self):
        u"""Gets the available_capacity of this Node.

        Capacity available to be assigned.  # noqa: E501

        :return: The available_capacity of this Node.
        :rtype: Capacity
        """
        return self._available_capacity

    @available_capacity.setter
    def available_capacity(self, available_capacity):
        u"""Sets the available_capacity of this Node.

        Capacity available to be assigned.  # noqa: E501

        :param available_capacity: The available_capacity of this Node.
        :type available_capacity: Capacity
        """

        self._available_capacity = available_capacity

    @property
    def cost_characteristic(self):
        u"""Gets the cost_characteristic of this Node.

        The list of costs where each cost relates to some aspect of the TopologicalEntity.  # noqa: E501

        :return: The cost_characteristic of this Node.
        :rtype: List[CostCharacteristic]
        """
        return self._cost_characteristic

    @cost_characteristic.setter
    def cost_characteristic(self, cost_characteristic):
        u"""Sets the cost_characteristic of this Node.

        The list of costs where each cost relates to some aspect of the TopologicalEntity.  # noqa: E501

        :param cost_characteristic: The cost_characteristic of this Node.
        :type cost_characteristic: List[CostCharacteristic]
        """

        self._cost_characteristic = cost_characteristic

    @property
    def error_characteristic(self):
        u"""Gets the error_characteristic of this Node.

        Describes the degree to which the signal propagated can be errored.  Applies to TDM systems as the errored signal will be propagated and not packet as errored packets will be discarded.  # noqa: E501

        :return: The error_characteristic of this Node.
        :rtype: str
        """
        return self._error_characteristic

    @error_characteristic.setter
    def error_characteristic(self, error_characteristic):
        u"""Sets the error_characteristic of this Node.

        Describes the degree to which the signal propagated can be errored.  Applies to TDM systems as the errored signal will be propagated and not packet as errored packets will be discarded.  # noqa: E501

        :param error_characteristic: The error_characteristic of this Node.
        :type error_characteristic: str
        """

        self._error_characteristic = error_characteristic

    @property
    def loss_characteristic(self):
        u"""Gets the loss_characteristic of this Node.

        Describes the acceptable characteristic of lost packets where loss may result from discard due to errors or overflow. Applies to packet systems and not TDM (as for TDM errored signals are propagated unless grossly errored and overflow/underflow turns into timing slips).  # noqa: E501

        :return: The loss_characteristic of this Node.
        :rtype: str
        """
        return self._loss_characteristic

    @loss_characteristic.setter
    def loss_characteristic(self, loss_characteristic):
        u"""Sets the loss_characteristic of this Node.

        Describes the acceptable characteristic of lost packets where loss may result from discard due to errors or overflow. Applies to packet systems and not TDM (as for TDM errored signals are propagated unless grossly errored and overflow/underflow turns into timing slips).  # noqa: E501

        :param loss_characteristic: The loss_characteristic of this Node.
        :type loss_characteristic: str
        """

        self._loss_characteristic = loss_characteristic

    @property
    def repeat_delivery_characteristic(self):
        u"""Gets the repeat_delivery_characteristic of this Node.

        Primarily applies to packet systems where a packet may be delivered more than once (in fault recovery for example).  It can also apply to TDM where several frames may be received twice due to switching in a system with a large differential propagation delay.  # noqa: E501

        :return: The repeat_delivery_characteristic of this Node.
        :rtype: str
        """
        return self._repeat_delivery_characteristic

    @repeat_delivery_characteristic.setter
    def repeat_delivery_characteristic(self, repeat_delivery_characteristic):
        u"""Sets the repeat_delivery_characteristic of this Node.

        Primarily applies to packet systems where a packet may be delivered more than once (in fault recovery for example).  It can also apply to TDM where several frames may be received twice due to switching in a system with a large differential propagation delay.  # noqa: E501

        :param repeat_delivery_characteristic: The repeat_delivery_characteristic of this Node.
        :type repeat_delivery_characteristic: str
        """

        self._repeat_delivery_characteristic = repeat_delivery_characteristic

    @property
    def delivery_order_characteristic(self):
        u"""Gets the delivery_order_characteristic of this Node.

        Describes the degree to which packets will be delivered out of sequence. Does not apply to TDM as the TDM protocols maintain strict order.  # noqa: E501

        :return: The delivery_order_characteristic of this Node.
        :rtype: str
        """
        return self._delivery_order_characteristic

    @delivery_order_characteristic.setter
    def delivery_order_characteristic(self, delivery_order_characteristic):
        u"""Sets the delivery_order_characteristic of this Node.

        Describes the degree to which packets will be delivered out of sequence. Does not apply to TDM as the TDM protocols maintain strict order.  # noqa: E501

        :param delivery_order_characteristic: The delivery_order_characteristic of this Node.
        :type delivery_order_characteristic: str
        """

        self._delivery_order_characteristic = delivery_order_characteristic

    @property
    def unavailable_time_characteristic(self):
        u"""Gets the unavailable_time_characteristic of this Node.

        Describes the duration for which there may be no valid signal propagated.  # noqa: E501

        :return: The unavailable_time_characteristic of this Node.
        :rtype: str
        """
        return self._unavailable_time_characteristic

    @unavailable_time_characteristic.setter
    def unavailable_time_characteristic(self, unavailable_time_characteristic):
        u"""Sets the unavailable_time_characteristic of this Node.

        Describes the duration for which there may be no valid signal propagated.  # noqa: E501

        :param unavailable_time_characteristic: The unavailable_time_characteristic of this Node.
        :type unavailable_time_characteristic: str
        """

        self._unavailable_time_characteristic = unavailable_time_characteristic

    @property
    def server_integrity_process_characteristic(self):
        u"""Gets the server_integrity_process_characteristic of this Node.

        Describes the effect of any server integrity enhancement process on the characteristics of the TopologicalEntity.  # noqa: E501

        :return: The server_integrity_process_characteristic of this Node.
        :rtype: str
        """
        return self._server_integrity_process_characteristic

    @server_integrity_process_characteristic.setter
    def server_integrity_process_characteristic(self, server_integrity_process_characteristic):
        u"""Sets the server_integrity_process_characteristic of this Node.

        Describes the effect of any server integrity enhancement process on the characteristics of the TopologicalEntity.  # noqa: E501

        :param server_integrity_process_characteristic: The server_integrity_process_characteristic of this Node.
        :type server_integrity_process_characteristic: str
        """

        self._server_integrity_process_characteristic = server_integrity_process_characteristic

    @property
    def latency_characteristic(self):
        u"""Gets the latency_characteristic of this Node.

        The effect on the latency of a queuing process. This only has significant effect for packet based systems and has a complex characteristic.  # noqa: E501

        :return: The latency_characteristic of this Node.
        :rtype: List[LatencyCharacteristic]
        """
        return self._latency_characteristic

    @latency_characteristic.setter
    def latency_characteristic(self, latency_characteristic):
        u"""Sets the latency_characteristic of this Node.

        The effect on the latency of a queuing process. This only has significant effect for packet based systems and has a complex characteristic.  # noqa: E501

        :param latency_characteristic: The latency_characteristic of this Node.
        :type latency_characteristic: List[LatencyCharacteristic]
        """

        self._latency_characteristic = latency_characteristic

    @property
    def owned_node_edge_point(self):
        u"""Gets the owned_node_edge_point of this Node.


        :return: The owned_node_edge_point of this Node.
        :rtype: List[NodeEdgePoint]
        """
        return self._owned_node_edge_point

    @owned_node_edge_point.setter
    def owned_node_edge_point(self, owned_node_edge_point):
        u"""Sets the owned_node_edge_point of this Node.


        :param owned_node_edge_point: The owned_node_edge_point of this Node.
        :type owned_node_edge_point: List[NodeEdgePoint]
        """

        self._owned_node_edge_point = owned_node_edge_point

    @property
    def aggregated_node_edge_point(self):
        u"""Gets the aggregated_node_edge_point of this Node.


        :return: The aggregated_node_edge_point of this Node.
        :rtype: List[str]
        """
        return self._aggregated_node_edge_point

    @aggregated_node_edge_point.setter
    def aggregated_node_edge_point(self, aggregated_node_edge_point):
        u"""Sets the aggregated_node_edge_point of this Node.


        :param aggregated_node_edge_point: The aggregated_node_edge_point of this Node.
        :type aggregated_node_edge_point: List[str]
        """

        self._aggregated_node_edge_point = aggregated_node_edge_point

    @property
    def node_rule_group(self):
        u"""Gets the node_rule_group of this Node.


        :return: The node_rule_group of this Node.
        :rtype: List[NodeRuleGroup]
        """
        return self._node_rule_group

    @node_rule_group.setter
    def node_rule_group(self, node_rule_group):
        u"""Sets the node_rule_group of this Node.


        :param node_rule_group: The node_rule_group of this Node.
        :type node_rule_group: List[NodeRuleGroup]
        """

        self._node_rule_group = node_rule_group

    @property
    def encap_topology(self):
        u"""Gets the encap_topology of this Node.


        :return: The encap_topology of this Node.
        :rtype: str
        """
        return self._encap_topology

    @encap_topology.setter
    def encap_topology(self, encap_topology):
        u"""Sets the encap_topology of this Node.


        :param encap_topology: The encap_topology of this Node.
        :type encap_topology: str
        """

        self._encap_topology = encap_topology

    @property
    def layer_protocol_name(self):
        u"""Gets the layer_protocol_name of this Node.


        :return: The layer_protocol_name of this Node.
        :rtype: List[str]
        """
        return self._layer_protocol_name

    @layer_protocol_name.setter
    def layer_protocol_name(self, layer_protocol_name):
        u"""Sets the layer_protocol_name of this Node.


        :param layer_protocol_name: The layer_protocol_name of this Node.
        :type layer_protocol_name: List[str]
        """
        allowed_values = [u"OTSiA", u"OCH", u"OTU", u"ODU", u"ETH", u"ETY", u"DSR", u"SDM"]  # noqa: E501
        if not set(layer_protocol_name).issubset(set(allowed_values)):
            raise ValueError(
                u"Invalid values for `layer_protocol_name` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(u", ".join(imap(str, set(layer_protocol_name) - set(allowed_values))),  # noqa: E501
                        u", ".join(imap(str, allowed_values)))
            )

        self._layer_protocol_name = layer_protocol_name
