# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.available_core import AvailableCore
from tapi_server.models.available_transceiver import AvailableTransceiver
from tapi_server import util


class SdmPool(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, available_core: List[AvailableCore]=None, available_transceiver: AvailableTransceiver=None ):  # noqa: E501
        """SdmPool - a model defined in Swagger

        :param available_core: The available_core of this NodeEdgePoint.  # noqa: E501
        :type available_core: List[AvailableCore]
        :param available_transceiver: The available_transceiver of this NodeEdgePoint.  # noqa: E501
        :type available_transceiver: AvailableTransceiver
        """
        self.swagger_types = {
            'available_core': List[AvailableCore],
            'available_transceiver': AvailableTransceiver
        }

        self.attribute_map = {
            'available_core': 'available-core',
            'available_transceiver': 'available-transceiver'
        }

        self._available_core = available_core
        self._available_transceiver = available_transceiver


    @classmethod
    def from_dict(cls, dikt) -> 'SdmPool':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The node-edge-point of this NodeEdgePoint.  # noqa: E501
        :rtype: NodeEdgePoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def available_core(self) -> List[AvailableCore]:
        """Gets the available_core of this NodeEdgePoint.

        List of available_core. 
        :return: The available_core of this NodeEdgePoint.
        :rtype: List[AvailableCore]
        """
        return self._available_core

    @available_core.setter
    def available_core(self, available_core: List[AvailableCore]):
        """Sets the available_core of this NodeEdgePoint.

        List of AvailableCore. 
        
        :param name: The available_core of this NodeEdgePoint.
        :type name: List[AvailableCore]
        """

        self._available_core = available_core

    @property
    def available_transceiver(self) -> AvailableTransceiver:
        """Gets the available_transceiver of this NodeEdgePoint.

        :return: The available_transceiver of this NodeEdgePoint.
        :rtype: AvailableTransceiver
        """
        return self._available_transceiver

    @available_transceiver.setter
    def available_transceiver(self, available_transceiver: AvailableTransceiver):
        """Sets the available_transceiver of this NodeEdgePoint.

        :param available_transceiver: The available_transceiver of this NodeEdgePoint.
        :type available_transceiver: AvailableTransceiver
        """

        self._available_transceiver = available_transceiver

   